branch-defaults:
  master:
    environment: GamePublish-env
environment-defaults:
  GamePublish-env:
    branch: master
    repository: origin
global:
  application_name: GamePublish
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.0 running on
    64bit Amazon Linux/2.4.2
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
